### ISSUE TITLE
feature request: allow tmtop to just take the RPC url without specifying --rpc-host XXX

### ISSUE THREAD

**Issue by PFC-developer** [QuokkaStake/tmtop#20]
pvtop does this as it makes the much tool simpler to use.

also the --rpc-host argument should be the first flag on the help, or even on the usage.

eg.
$ tmtop https://rpc.orai.pfc.zone:443

thanks!

**Comment by freak12techno** [comment]
Makes sense, will add at some point. Thanks for suggesting!
