### ISSUE TITLE
Smileys are not displayed

### ISSUE THREAD

**Issue by IIIyJIeP** [QuokkaStake/tmtop#9]
Smileys and icons are not displayed, what could be the problem?
![image](https://github.com/QuokkaStake/tmtop/assets/46248801/623dac4a-c7ce-49b7-a7ae-1851f6efbb87)

**Comment by freak12techno** [comment]
@IIIyJIeP this looks like a terminal/shell issue I'd say, can you try running it on another system/terminal? I am gonna look at it a bit later thoroughly

**Comment by IIIyJIeP** [comment]
Noticed that this happens when I run tmtop on a remote machine via ssh. I tried it on several machines with Debian 12 and Ubuntu 22.04 (By the way, the same pvtop works fine in these conditions).

If I run tmtop in the local machine terminal, there are no problems

zsh was used in all cases

**Comment by freak12techno** [comment]
Weird as I also am using both Debian and Ubuntu on my servers and never had issues so far.

Anyways, this should be an issue with the shell or something similar, meanwhile there should be definitely a way to disable emojis via a flag or something, I'll add this in a while.

Thanks for adding the context on pvtop working fine here, I'll check as well how these two are different.

**Comment by freak12techno** [comment]
@IIIyJIeP okay so I pushed the v1.4.1 release, which is going to be tagged soon that allows running tmtop with --disable-emojis that should fallback to plain ASCII symbols which should work everywhere.

Not sure about what causes this, but it seems like there may be some fonts missing; try checking this one https://www.reddit.com/r/voidlinux/comments/xlr6fa/emojis_dont_show_in_terminal_after_updating_the/ to see if it works for you.
